### ISSUE TITLE
Parabolic won't open

### ISSUE THREAD

**Issue by schustobias** [NickvisionApps/Parabolic#620]
### Hi. When I try to open parabolic I get the following error message: 

** (process:776): WARNING **: 17:34:56.405: Failed to connect to bus: Could not connect: No such file or directory

(process:2): Gdk-WARNING **: 17:34:56.405: Settings portal not found: Error receiving data: Connection reset by peer

** (process:776): WARNING **: 17:34:56.406: Failed to connect to bus: Could not connect: No such file or directory

** (process:776): WARNING **: 17:34:56.423: Failed to connect to bus: Could not connect: No such file or directory

** (process:776): WARNING **: 17:34:56.514: Failed to connect to bus: Could not connect: No such file or directory

** (process:776): WARNING **: 17:34:56.528: Failed to connect to bus: Could not connect: No such file or directory

(org.nickvision.tubeconverter:2): Gtk-WARNING **: 17:34:56.528: Unable to acquire session bus: Error receiving data: Connection reset by peer

** (process:776): WARNING **: 17:34:56.532: Failed to connect to bus: Could not connect: No such file or directory
UnhandledException - unhandled exception: GLib.GException: Error receiving data: Connection reset by peer
   at GLib.Error.ThrowOnError(ErrorHandle error)
   at Gio.DBusConnection.Get(BusType busType)
   at NickvisionTubeConverter.GNOME.Views.MainWindow..ctor(Builder builder, MainWindowController controller, Application application) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/MainWindow.cs:line 51
   at NickvisionTubeConverter.GNOME.Views.MainWindow..ctor(MainWindowController controller, Application application) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/MainWindow.cs:line 169
   at NickvisionTubeConverter.GNOME.Program.OnActivate(Application sender, EventArgs e) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Program.cs:line 111
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass3_0.<ScheduleAction>b__0()

### Second error I got trying to open it with sudo -i:

UnhandledException - unhandled exception: GLib.GException: Error spawning command line “dbus-launch --autolaunch=bc4f37307a734606816a78875f91ea5f --binary-syntax --close-stderr”: Child process exited with code 1
   at GLib.Error.ThrowOnError(ErrorHandle error)
   at Gio.DBusConnection.Get(BusType busType)
   at NickvisionTubeConverter.GNOME.Views.MainWindow..ctor(Builder builder, MainWindowController controller, Application application) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/MainWindow.cs:line 51
   at NickvisionTubeConverter.GNOME.Views.MainWindow..ctor(MainWindowController controller, Application application) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Views/MainWindow.cs:line 169
   at NickvisionTubeConverter.GNOME.Program.OnActivate(Application sender, EventArgs e) in /run/build/org.nickvision.tubeconverter/NickvisionTubeConverter.GNOME/Program.cs:line 111
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass1_0.<Post>b__0()
   at GLib.Internal.MainLoopSynchronizationContext.<>c__DisplayClass3_0.<ScheduleAction>b__0()

**Comment by nlogozzo** [comment]
@fsobolev

**Comment by fsobolev** [comment]
Well, the app can't connect to session bus... No idea what causes this, but I think it's something that can't be fixed on our side anyway, that's something wrong with system configuration.

**Comment by schustobias** [comment]
Sorry to bother you. After browsing some stackexchange I managed to somehow fix the issue.
