### ISSUE TITLE
[Bug] Parabolic crashes when using Download specific timeframe option

### ISSUE THREAD

**Issue by JoseBritto** [NickvisionApps/Parabolic#631]
Here is the exception thrown:
```
System.ArgumentException: TimeSpan does not accept floating point Not-a-Number values.
   at System.TimeSpan.FromSeconds(Double value)
   at NickvisionTubeConverter.GNOME.Views.AddDownloadDialog.<.ctor>b__52_9(Object sender, NotifySignalArgs e) in /home/britto/Source/C#/Parabolic/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs:line 173
   at GObject.Signal`2.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

Happens when MediaInfo.Duration contains NaN as its value at this line: 
https://github.com/NickvisionApps/Parabolic/blob/40612b3fcb117b10087b468502586596b29541d2/NickvisionTubeConverter.GNOME/Views/AddDownloadDialog.cs#L173

Use this url to reproduce: https://einthusan.tv/movie/watch/3034/?lang=malayalam

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.11.0-beta1
