### ISSUE TITLE
Abrupt closure when clicking on "Help"

### ISSUE THREAD

**Issue by romulo-godoi** [NickvisionApps/Parabolic#864]
Hello everyone. I would like to report the following issue that occurs on Ubuntu 24.04.1 LTS with version 2024.5.0 of Parabolic, installed via Snap package.

When you click on "Help" the application simply closes without opening any page or browser.

**Comment by nlogozzo** [comment]
@soumyaDghosh

**Comment by soumyaDghosh** [comment]
Any error log? It worked for me though.

**Comment by soumyaDghosh** [comment]
@nlogozzo 

```bash
UnhandledException - unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at NickvisionTubeConverter.Shared.Helpers.DocumentationHelpers.GetHelpURL(String pageName) in /build/tube-converter/parts/tube-converter/src/NickvisionTubeConverter.Shared/Helpers/DocumentationHelpers.cs:line 30
   at NickvisionTubeConverter.GNOME.Views.MainWindow.<.ctor>b__19_16(SimpleAction sender, ActivateSignalArgs e) in /build/tube-converter/parts/tube-converter/src/NickvisionTubeConverter.GNOME/Views/MainWindow.cs:line 164
   at GObject.Signal`2.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, IntPtr paramValuesData, IntPtr invocationHint, IntPtr userData)
```
This is the error log, and this from the last stable release 2024.5.0

So, may be I should try pushing some release candidates to stable. As I don't to push the latest one to stable yet.

**Comment by nlogozzo** [comment]
The latest snap version on stable should be 2024.10.0 

I pushed it when I did the release.

**Comment by romulo-godoi** [comment]
It could be that. The Snap package marked as stable is version 2024.5.0, while version 2024.10.0 is in the edge channel. Maybe this bug doesn't exist in version 2024.10.0, but for some reason, the version in the Ubuntu store hasn't been updated yet.
![Captura de tela de 2024-10-05 18-00-45](https://github.com/user-attachments/assets/c12c394d-6abb-456c-81bd-5d7731325cae)

**Comment by soumyaDghosh** [comment]
> The latest snap version on stable should be 2024.10.0 
> 
> I pushed it when I did the release.

I reverted it due to the auto connection issue.

**Comment by nlogozzo** [comment]
Ah so this issue has been fixed with V2024.10.0

Please wait for that to be pushed to snap or use the flatpak version.

**Comment by nlogozzo** [comment]
> I reverted it due to the auto connection issue.

Any idea when this will be fixed?

2024.5.0 uses an old yt-dlp and has many bugs were most websites, even YouTube sometimes, don't validate correctly.

2024.10.0 is a must.

**Comment by soumyaDghosh** [comment]
> > I reverted it due to the auto connection issue.
> 
> Any idea when this will be fixed?
> 
> 2024.5.0 uses an old yt-dlp and has many bugs were most websites, even YouTube sometimes, don't validate correctly.
> 
> 2024.10.0 is a must.

Let me temporarily revert to core22 then

**Comment by soumyaDghosh** [comment]
fixed
